config/routes.rb
Rails.application.routes.draw do
  get 'meters/index'
  # get 'meters/import'
  resources :meters do
    collection { post :import }
  end
  get 'pdf' ,to: 'meters#pdf'
  root to: 'meters#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meter.rb
class Meter < ApplicationRecord

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |meter|
        csv << meter.attributes.values_at(*column_names)
      end
    end
  end
  
  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      meter = find_by_id(row["id"]) || new
      meter.attributes = row.to_hash
      meter.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Roo::CSV.new(file.path, packed: nil, file_warning: :ignore)
    when ".xls" then Roo::Excel.new(file.path, packed: nil, file_warning: :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, packed: nil, file_warning: :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/meters_controller.rb
class MetersController < ApplicationController
  def index
    @meters = Meter.all
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => 'test', :template => 'meters/pdf.html.erb'
      end
    end
  end

  def pdf
    @meters = Meter.all
  end
  
  def import
    Meter.delete_all
    Meter.import(params[:file])
    redirect_to root_url, notice: "Xlsx imported."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meters_helper.rb
module MetersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Maintance</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/meters/index.html.erb
<h1>Meter Reading </h1>

<table class="table table-striped">
  <tr>
    <th>Flat No</th>
    <th>New Unit</th>
    <th>Old Unit</th>
    <th>Used Unit</th>
    <th>Rate Per Unit</th>
    <th>Amount</th>
    <th>Fix Charge</th>
    <th>Total</th>
  </tr>
<% @meters.each do |meter| %>
  <tr>
    <td><%= meter.flat_no %></td>
    <td><%= meter.new_unit %></td>
    <td><%= meter.old_unit %></td>
    <td><%= meter.used_unit %></td>
    <td><%= meter.rate_perunit %></td>
    <td><%= meter.amount %></td>
    <td><%= meter.fix_charge %></td>
    <td><%= meter.total %></td>   
  </tr>
<% end %>
</table>

<h2>Import Reading</h2>

<%= form_tag import_meters_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>
<p><%= link_to "Printable Receipt (PDF)", meters_path(@meters, format: "pdf"), target: '_blank' %></p>

app/views/meters/pdf.html.erb
<meta charset="UTF-8">
<%= wicked_pdf_stylesheet_link_tag "bootstrap.css" %>
<% flag = 1 %>
<% @meters.each do |meter| %>
  <% flag = flag + 1%>
  <div class="column <%= flag.even? ? 'even' : ''%>" lang="gu">
    <table class="table table-striped" border="2" >
      <tr class="table-header">
        <th colspan="3" lang="gu">ધી સુરમ્ય રેસીડેન્સી <br>કો. ઓ. હા. સર્વિસ સોસાયટી લી.</th>
      </tr>
      <tr class="table-date">
        <th colspan="3">નધણ/એ.એચ.એમ./સા. (હા)૧૦૦૬૭, તા.૨૦-૦૬-૨૦૧૭</th>
      </tr>
      <tr class="table-address">
        <th colspan="3">'સુરમ્ય રેસીડેન્સી',સુવાસ રેસીડેન્સીની પાછળ, નિકોલ ગામ રોડ, નિકોલ, અમદાવાદ-૩૮૨૩૫૦.</th>
      </tr>
      <tr>
      <th style="text-align:left;width:33%;">પહોંચ નં. : <%= meter.receipt_no %></th>
      <th style="text-align:left;width:33%;">ફ્લેટ નં. : <%= meter.flat_no %></th>
      <th style="text-align:left;width:34%;">તા.<%= meter.date %></th>
      </tr>
      <tr>
        <th colspan="3" style="text-align:left;">નામ :<%= meter.name %></th>
      </tr>
      <tr class="table-data table-backcolor-darkred">
        <th colspan="2">વિગત</th>
        <th>રકમ રૂ.</th>
      </tr>
      <tr class="table-data">
        <td colspan="2">હાલ નું વાંચન</td>
        <td><%= meter.new_unit %></td>
      </tr>
      <tr class="table-data">
        <td colspan="2">અગાઉ નું વાંચન</td>
        <td><%= meter.old_unit %></td>
      </tr>
      <tr class="table-data">
        <td colspan="2">વપરાયેલ યુનિટ</td>
        <td><%= meter.used_unit %></td>
      </tr>
      <tr class="table-data">
        <td colspan="2">યુનિટ નો ભાવ</td>
        <td><%= meter.rate_perunit %></td>
      </tr>
      <tr class="table-data">
        <td colspan="2">પાણીનું બિલ</td>
        <td><%= meter.amount %></td>
      </tr>
      <tr class="table-data">
        <td colspan="2">મેન્ટેનેન્સ ચાર્જ</td>
        <td><%= meter.fix_charge %></td>
      </tr>
      <tr class="table-data table-backcolor-red">
        <td colspan="2">ટોટલ</td>
        <td><%= meter.total %></td>
      </tr>
    </table>
  </div>
<% end %>